#!/usr/bin/env node
/**
 * 从 init-cli skill 的 assets/schemas 生成内嵌资源模块。
 * skills/engineering/init-cli/assets/schemas 是模板的单一事实来源；
 * 本脚本在构建期运行，保证 spect init 的产出与 assets 完全一致。
 */
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const assetsDir = path.resolve(here, '../../skills/engineering/init-cli/assets/schemas');
const out = path.resolve(here, '../src/core/embedded-assets.ts');

const configYaml = readFileSync(path.join(assetsDir, 'spec-driven/config.yaml'), 'utf8');
const schemaYaml = readFileSync(path.join(assetsDir, 'schema.yaml'), 'utf8');
const templateNames = ['proposal', 'spec', 'design', 'tasks'];
const templates = Object.fromEntries(
  templateNames.map((name) => [
    name,
    readFileSync(path.join(assetsDir, 'spec-driven/templates', `${name}.md`), 'utf8'),
  ])
);

const lines = [
  '// Generated by scripts/embed-schemas.mjs from skills/engineering/init-cli/assets/schemas.',
  '// Do not edit by hand — edit the assets and re-run `npm run build`.',
  '',
  `export const EMBEDDED_CONFIG_YAML = ${JSON.stringify(configYaml)};`,
  '',
  `export const EMBEDDED_SCHEMA_YAML = ${JSON.stringify(schemaYaml)};`,
  '',
  'export const EMBEDDED_TEMPLATES: Record<string, string> = {',
  ...templateNames.map((name) => `  ${name}: ${JSON.stringify(templates[name])},`),
  '};',
  '',
];

writeFileSync(out, lines.join('\n'));
console.log(`embedded assets written: ${path.relative(process.cwd(), out)}`);
